name: codeverse-synth
version: 0.0.3
base: core18
architectures:
  - build-on: armhf
summary: Sound maker for the Codeverse studios
description: |
  An audio player and sound generator which exposes a web API, runs on a Codeverse module and used within the Codeverse Studios
confinement: strict
grade: stable
build-packages: [gcc]

apps:
  web-api:
    command: webserver www
    daemon: simple
    restart-condition: always
    plugs:
      - pulseaudio
      - home
      - network-bind

  pulseaudio-example:
    command: bin/client-wrapper usr/bin/pulseaudio-example
    plugs:
      - pulseaudio
      - home

  enable-sound-card:
    command: enable-sound-card
    plugs:
      - gpio-memory-control

parts:
  web-api:
    source: .
    plugin: go
    go-importpath: github.com/americademy/synth-snap

  enable-sound-card:
    source: .
    source-subdir: enable-sound-card
    plugin: make

  pulseaudio-example-common:
    plugin: dump
    source: overlay

  pulseaudio-example:
    plugin: cmake
    source: pulseaudio-example
    build-packages:
      - build-essential
      - libpulse-dev

  mpg123:
    plugin: nil
    stage-packages:
      - mpg123


